# docker-compose.yml (新架構)
version: '3.8'

services:
  traefik:
    image: traefik:v2.11
    container_name: ocr-traefik
    restart: unless-stopped
    ports:
      - "${DASHBOARD_PORT}:8080"
      - "${HTTPS_PORT}:${TRAEFIK_HTTPS_PORT:-443}"
      - "${HTTP_PORT:-8080}:80"
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.websecure.address=:${TRAEFIK_HTTPS_PORT:-443}"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--accesslog=true"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./registry/certs:/certs:ro
      - ./registry/auth:/auth:ro
    networks:
      - registry-net

  registry:
    image: registry:2
    container_name: ocr-registry
    restart: unless-stopped
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin=['https://${REGISTRY_DOMAIN}:${HTTPS_PORT}']
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods=['HEAD', 'GET', 'OPTIONS', 'DELETE']
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers=['Authorization', 'Accept']
      - REGISTRY_HTTP_HEADERS_Access-control-Allow-Credentials=['true']
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
    volumes:
      - ./registry/data:/data
      - ./registry/auth:/auth:ro
      - ./registry/certs:/certs:ro
    networks:
      - registry-net
    labels:
      - "traefik.enable=true"
      # API Router
      - "traefik.http.routers.registry-api.rule=Host(`${REGISTRY_DOMAIN}`) && PathPrefix(`/v2`)"
      - "traefik.http.routers.registry-api.entrypoints=websecure"
      - "traefik.http.routers.registry-api.service=registry-api"
      - "traefik.http.routers.registry-api.priority=10"
      - "traefik.http.routers.registry-api.tls=true"
      - "traefik.http.routers.registry-api.middlewares=registry-auth"
      # API Service
      - "traefik.http.services.registry-api.loadbalancer.server.port=5000"
      # Auth Middleware
      - "traefik.http.middlewares.registry-auth.basicauth.usersfile=/auth/htpasswd"
      - "traefik.http.middlewares.registry-auth.basicauth.realm=Registry Realm"
      # --- [新增] 解決上傳逾時問題 ---
      - "traefik.http.services.registry-api.loadbalancer.server.forwardingTimeouts.idleTimeout=10m"
      - "traefik.http.services.registry-api.loadbalancer.server.forwardingTimeouts.responseHeaderTimeout=10m"

  registry-ui:
    image: joxit/docker-registry-ui:main
    container_name: ocr-registry-ui
    restart: unless-stopped
    environment:
      - REGISTRY_TITLE=${REGISTRY_UI_TITLE}
      - DELETE_IMAGES=true
      - NGINX_LISTEN_PORT=80
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
      - SHOW_CONTENT_DIGEST=true
      - USE_CONTROL_BUTTON=true
    volumes:
      - ./registry/auth:/auth:ro
    networks:
      - registry-net
    labels:
      - "traefik.enable=true"
      # UI Router
      - "traefik.http.routers.registry-ui.rule=Host(`${REGISTRY_DOMAIN}`)"
      - "traefik.http.routers.registry-ui.entrypoints=websecure"
      - "traefik.http.routers.registry-ui.service=registry-ui"
      - "traefik.http.routers.registry-ui.priority=1"
      - "traefik.http.routers.registry-ui.tls=true"
      # UI Service
      - "traefik.http.services.registry-ui.loadbalancer.server.port=80"

volumes:
  ts-state:
    driver: local

networks:
  registry-net:
    driver: bridge
