http:
  routers:
    registry-router:
      rule: "Host(`${REGISTRY_DOMAIN}`)"
      entryPoints:
        - registry
      service: registry-service
      tls: {}

    registry-ui-router:
      rule: "Host(`${REGISTRY_DOMAIN}`)"
      entryPoints:
        - registryui
      service: registry-ui-service
      tls: {}

  services:
    registry-service:
      loadBalancer:
        servers:
          - url: "https://localhost:5000"
        serversTransport: insecureskipverify@file

    registry-ui-service:
      loadBalancer:
        servers:
          - url: "http://localhost:80"
